### 1. 북로그 생성 (도서 기부)
POST http://localhost:8081/backend/bookLog/donateBook
Content-Type: application/json

{
    "lockerNo": 3,
    "detailLockerNo": 7,
    "accountNo": 2,
    "bookIsbn": "9788960777330"
}

### 2. 해당 보관함의 ture 모든 북로그 조회
GET http://localhost:8081/backend/bookLog/locker/3

### 3. 북로그 (도서 수령)
POST http://localhost:8081/backend/bookLog/receiveBook
Content-Type: application/json

{
    "bookLogNo": 1,
    "accountNo": 2,
    "bookIsbn": "8984993751",
    "lockerNo": 1,
    "detailLockerNo": 1
}

### 4. 단일 도서의 전체 리뷰 조회
GET http://localhost:8081/backend/bookLog/review/8984993751

### 5. 단일 보관함의 전체 도서 조회
GET http://localhost:8081/backend/bookLog/locker/1

### 6. 단일 북로그 조회
GET http://localhost:8081/backend/bookLog/1

### 7. 단일 회원의 전체 북로그 조회
GET http://localhost:8081/backend/bookLog/account/1

### 8. 전체 북로그 조회
GET http://localhost:8081/backend/bookLog