### 1. 전체 북로그 조회
GET http://localhost:8081/backend/bookLog

### 2. 단일 북로그 조회
GET http://localhost:8081/backend/bookLog/{{bookLogNo}}

### 3. 단일 회원의 전체 북로그 조회
GET http://localhost:8081/backend/bookLog/account/{{accountNo}}

### 4. 단일 보관함의 전체 북로그 조회
GET http://localhost:8081/backend/bookLog/locker/{{lockerNo}}

### 5. 단일 도서의 전체 리뷰 조회
GET http://localhost:8081/backend/bookLog/review/{{bookIsbn}}

### 6. 북로그 생성 (도서 기부)
POST http://localhost:8081/backend/bookLog/donateBook
Content-Type: application/json

{
    "lockerNo": 3,
    "detailLockerNo": 1,
    "accountNo": 2,
    "bookIsbn": "9788966260959"
}

### 7. 북로그 (도서 수령)
POST http://localhost:8081/backend/bookLog/receiveBook
Content-Type: application/json

{
    "bookLogNo": 6,
    "accountNo": 2,
    "bookIsbn": "9788966260959",
    "lockerNo": 3,
    "detailLockerNo": 1
}

### 8. 위시리스트 추가
POST http://localhost:8081/backend/bookLog/wishList
Content-Type: application/json

{
    "bookLogNo": 1,
    "accountNo": 2
}






